image: node:24-alpine

stages:
  - deploy

deploy_vercel:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  script:
    - npm install -g vercel
    - vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
    - vercel build --prod --token="$VERCEL_TOKEN"
    - vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
  environment:
    name: production
    url: https://precificador-estimativa.vercel.app
